name: 🚀 Deploy to EC2

on:
  workflow_run:
    workflows: ["CI Pipeline with GHCR"]
    types: [completed]

jobs:
  deploy:
    name: 🚀 Deploy to EC2
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: 🧾 Decode SSH key and prepare file
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 -d > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: 🔐 Connect and deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key_path: ./ec2_key.pem         # ✅ use the decoded file
          script: |
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            docker pull ghcr.io/${{ github.actor }}/weather-frontend:latest
            docker pull ghcr.io/${{ github.actor }}/weather-backend:latest

            docker stop weather-frontend || true
            docker rm weather-frontend || true
            docker stop weather-backend || true
            docker rm weather-backend || true

            docker run -d --name weather-frontend -p 80:3000 ghcr.io/${{ github.actor }}/weather-frontend:latest

            docker run -d --name weather-backend -p 5000:5000 -e WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }} ghcr.io/${{ github.actor }}/weather-backend:latest
